### PR TITLE
Ubisoft UPlay support added

### PR DESCRIPTION
**Pull request by junkhacker**
config for cache support for uPlay. has this been tested?

### CODE REVIEW

**Comment by wendelj** [comment]
I didn't see this pull request before I blew away my repo to recreate it. Sorry if that screwed up this pull request.
I tested this config with one game download and it seemed to work. (Used The Disivion for the test game.)

**Comment by junkhacker** [comment]
do you have a listing of the dns entries you used for uPlay?

**Comment by wendelj** [comment]
Just one dns entry was needed for uplaypc-s-ubisoft.cdn.ubi.com.

**Comment by junkhacker** [comment]
thank you

**Pull request merged**
